### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by samuelasf** [terreng/simple-web-server#101] opened 2022-10-01 09:56 UTC
the file upload is not working. Tried configuring with all tools and tried to upload in more than one navigator

**Comment by ethanaobrien** [comment] 2022-10-01 14:02
Could you include a video? What OS are you using? What version are you running?

**Comment by samuelasf** [comment] 2022-10-01 14:21
I have from catalina until monterrey. There is no “uploado button”, drag an drop and post does not work. I do not known if I am doing somthing wrong

Enviado do meu iPhone

Em 1 de out. de 2022, à(s) 11:03, ethanaobrien ***@***.***> escreveu:

﻿

Could you include a video? What OS are you using? What version are you running?

**Comment by ethanaobrien** [comment] 2022-10-01 14:33
Chances are you're in the wrong place. Have you clicked the "create server" button?

**Comment by ethanaobrien** [comment] 2022-10-01 18:48
Oh sorry, I understand now, the POST request doesn't work like you think it would. The PUT request will upload files, not POST. Post requires additional coding and the documentation is not yet written for it.

**Comment by samuelasf** [comment] 2022-10-01 18:55
I promise making a video! If you want, choose ios version

Thanks for your attention

Enviado do meu iPhone

Em 1 de out. de 2022, à(s) 11:34, ethanaobrien ***@***.***> escreveu:

﻿

Chances are you're in the wrong place. Have you clicked the "create server" button?

**Comment by samuelasf** [comment] 2022-10-03 12:27
https://www.dropbox.com/s/nz3h5gy545f8qz2/screen.mov?dl=0


Em 1 de out. de 2022, à(s) 15:48, ethanaobrien ***@***.******@***.***>> escreveu:



Oh sorry, I understand now, the POST request doesn't work like you think it would. The PUT request will upload files, not POST. Post requires additional coding and the documentation is not yet written for it.

**Comment by samuelasf** [comment] 2022-10-03 12:28
Anexo disponível até 2 de nov. de 2022


Em 1 de out. de 2022, à(s) 15:48, ethanaobrien ***@***.******@***.***>> escreveu:


Clique para Baixar<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAZ_Fl3GsjWWSIfvXoxyNLk3DzPa8AZfS_VXy87htrYu6lVRNBIYT8jOI%2F%24%7Bf%7D%3Fo%3DAuvwi4DHkRFHjBghoyD9R1F9eeQW0COCvBIav24qMesO%26v%3D1%26x%3D3%26a%3DCAogRM8RIKm1mLM72gVpEpAyTdmIRaQzEndRykpM-9IhIlMSdhD41sfuuTAY-ObCwsMwIgEAKgkC6AMA_3oGcjRSBMPM9rxaBBPyM4hqJR6TKA_ejOAXZQNOzA-_3SkHDzI-tlA2GW_80Ezkk6-B8qmYITZyJYQwEszt0uAb5dY21cilsNGi99C1Xr1bkDBx04h_Evu4ZYL5sWY%26e%3D1667392123%26fl%3D%26r%3D0683B5EE-09AD-467E-9257-5807BCF81B07-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DBD333CA8-E066-4044-AC1A-0A59F4EA01F5%26p%3D47%26s%3Dkeq9sez8ljAa-Mf9FTQdIRA5BHk&uk=kOTiQIBBV0TzfdHbiXE_lQ&f=Gravac%CC%A7a%CC%83o%20de%20Tela%202022-10-03%20a%CC%80s%2009.23.52.mov&sz=37660730>
Gravação de Tela 2022-10-03 às 09.23.52.mov
37,7 MB

Oh sorry, I understand now, the POST request doesn't work like you think it would. The PUT request will upload files, not POST. Post requires additional coding and the documentation is not yet written for it.

**Comment by ethanaobrien** [comment] 2022-10-03 20:00
I'll take a look at this, thank you

**Comment by ethanaobrien** [comment] 2022-12-04 22:12
@terreng This was possibly fixed by #100, as I cannot reproduce this.

@samuelasf Would you mind trying to run from source and dragging and dropping a file like you did before?

**Comment by samuelasf** [comment] 2022-12-05 12:54
It is working perfectly

**Comment by terreng** [comment] 2022-12-11 05:37
Glad to hear it! The fix will be included in the next release, version 1.2. Thanks for reporting the issue!

**Closed by terreng** 2022-12-11 05:37 UTC
Labels: bug
