### ISSUE TITLE
put method - how to ?

### ISSUE THREAD

**Issue by WebScaffolder** [terreng/simple-web-server#47] opened 2022-01-10 12:48 UTC
var input = document.getElementById("app-logo");
      var file = input.files[0];
      var fd = new FormData();
      fd.append("file", file);
      function responseHandler(e) {
        console.log("readystate change", e);
      }
      var xhr = new XMLHttpRequest();
      xhr.open("PUT", "http://localhost:8080/uploads/logo", true);
      xhr.onreadystatechange = responseHandler;
      xhr.send(fd);

I had tried above to create logo image inside uploads/logo - shows strict-origin-when-cross-origin

**Comment by ethanaobrien** [comment] 2022-01-10 15:53
Is cors enabled?

**Comment by WebScaffolder** [comment] 2022-01-10 22:37
Hi Ethan, I did not find any checkbox both from master or new-ui brach. please let know as It needs fix.

**Comment by ethanaobrien** [comment] 2022-01-10 22:40
As far as I know, this isn't implemented yet (in the ui). You must enable it you must
1. Go to `%USERPROFILE%\AppData\Roaming\Simple Web Server` (in file explorer)
2. Find the server you want
3. add the option `upload` and set it to `true`
4. close and re-open the server

This is using the current master branch

**Comment by terreng** [comment] 2022-01-10 22:49
The `upload` option is in the new UI. It's called "Allow file upload" in the Advanced Rules section. 

@ethanaobrien We don't currently have an option for CORS. What did you mean when you asked if cors was enabled?

**Comment by ethanaobrien** [comment] 2022-01-10 22:51
>We don't currently have an option for CORS. What did you mean when you asked if cors was enabled?

Do we not? I have it implemented ([line 16](https://github.com/terreng/simple-web-server/blob/9797405c868819a28dda3c6e52c407d4beb2767f/WSC/handlers.js#L16))

**Comment by terreng** [comment] 2022-01-10 22:59
I don't think it came up in #1. What does it do?

**Comment by ethanaobrien** [comment] 2022-01-10 23:02
@terreng 
Oh, sorry. All cors does is set headers that allows websites to perform a request to it when it is outside of the domain (allows cross origin requests)

**Comment by terreng** [comment] 2022-01-10 23:03
Does it just set `Access-Control-Allow-Origin` to `*` or what?

**Comment by ethanaobrien** [comment] 2022-01-10 23:04
@terreng Correct

**Comment by terreng** [comment] 2022-01-10 23:11
I've added the missing CORS option to the [new-ui](https://github.com/terreng/simple-web-server/tree/new-ui) branch.

@WebScaffolder Please try enabling the new CORS option.

**Comment by WebScaffolder** [comment] 2022-01-10 23:15
Hi, CORS issue I just found while testing with PUT method for uploading file but as 'Access-Control-Allow-Origin' is a response header I need to build by editing WSC handler.js where it is missing from new ui brach and after/before build it shows entry not found even after SPA enabled.

**Comment by WebScaffolder** [comment] 2022-01-10 23:16
> I've added the missing CORS option to the [new-ui](https://github.com/terreng/simple-web-server/tree/new-ui) branch.
> 
> @WebScaffolder Please try enabling the new CORS option.

ok let me test.

**Comment by WebScaffolder** [comment] 2022-01-10 23:52
Hi, I can't test CORS problem from my vue SPA for PUT method while upload as you need to fix 404 - Not Found entry not found: /login First. But I had a test using postman and works like a charm. So only problem now SPA shows Not Found entry. Please let me know for new ui.

**Comment by ethanaobrien** [comment] 2022-01-10 23:55
could you post a picture of the code you are using to perform a PUT request. If I am correct (and I am (I wrote the handler)) the `404 - Not Found entry not found: /login` is only given off by a GET request

**Comment by WebScaffolder** [comment] 2022-01-11 01:02
Hi,

404 - Not Found entry not found: /login - yes you are right, this problem is with get request with github repository only. Soon i will send you a screenshot. 

Note that relese source has no problem with spa but i can not find WSC folder there.

**Comment by terreng** [comment] 2022-01-11 01:21
> Note that relese source has no problem with spa but i can not find WSC folder there.

The version 1.0.0 release uses completely different internals to run the web server, and that's why there isn't a WSC folder.

**Comment by WebScaffolder** [comment] 2022-01-11 02:04
Hi, Can you then just fix the old repository (where WSC present) for SPA support. Or update PUT method for version 1.0.0 so that as a developer we can use it for file uploading too.

**Comment by terreng** [comment] 2022-01-11 02:26
> Hi, Can you then just fix the old repository (where WSC present) for SPA support. Or update PUT method for version 1.0.0 so that as a developer we can use it for file uploading too.

We are not supporting the old version anymore. If there is an issue with the latest source, we'll fix it.

**Comment by WebScaffolder** [comment] 2022-01-11 03:01
just update the spa support for latest release I mean for new ui branch and we developer can use it. you already fixed put cors issue. thanks for that. but we developer need SPA support as well.

**Comment by WebScaffolder** [comment] 2022-01-11 09:17
Hi, any luck for improving new ui with SPA support as you packed WSC files  might for commercial release but without SPA it is not usable. please let me know.

**Comment by ethanaobrien** [comment] 2022-01-11 14:27
@terreng Would it be possible that we need the other spa options? (`optModRewriteNegate` and `optModRewriteTo`)
[line 270](https://github.com/terreng/simple-web-server/blob/9797405c868819a28dda3c6e52c407d4beb2767f/WSC/handlers.js#L270)

**Comment by terreng** [comment] 2022-01-11 16:34
@WebScaffolder Could you please clarify what exactly the issue is? Do you have a file at `/index.html`?

**Comment by WebScaffolder** [comment] 2022-01-11 17:10
![spa](https://user-images.githubusercontent.com/48052351/148988870-c120a922-531c-4a40-877e-3beaae2f7e06.gif)

hi, here I have attached the problem from new ui....but it dose not happen by release version.

**Comment by ethanaobrien** [comment] 2022-01-11 17:12
I think the problem is that we need to add the `optModRewriteNegate` option. Not sure what it does but I'm pretty sure this is it

**Comment by WebScaffolder** [comment] 2022-01-11 17:19
optModRewriteNegate - no idea but I did not see any config present either new ui or release 1.0.1, just to clarify to find out the problem.

**Comment by ethanaobrien** [comment] 2022-01-11 17:22
@WebScaffolder Would you mind opening google chrome and installing [this chrome extension](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en). Then could you set the mod rewrite options to whatever and send a screenshot when it works?

**Comment by WebScaffolder** [comment] 2022-01-11 17:23
ok, sure

**Comment by WebScaffolder** [comment] 2022-01-11 17:33
I think you are right. enabling negate it works with chrome
![negate](https://user-images.githubusercontent.com/48052351/148992630-75c96bb3-7f2a-4232-9a72-d435dc675755.gif)
 extension

**Comment by ethanaobrien** [comment] 2022-01-11 17:34
Awesome, thank you. @terreng What do you think?

**Comment by WebScaffolder** [comment] 2022-01-11 17:36
Can you just apply it for new ui branch. I will test and let you know if works.

**Comment by terreng** [comment] 2022-01-11 18:57
@WebScaffolder I've fixed the code on the new ui branch. It should work now. Thanks for bringing this to our attention. Please let us know if you have any other trouble, otherwise I'll close this issue.

@ethanaobrien The way the regex is written, it should always be negated. I'm going to add an option to choose which page to rewrite to, called `rewriteTo`.

**Comment by WebScaffolder** [comment] 2022-01-11 21:04
it doesn't work with new changes. and i tried to write below code but no luck -

if (this.app.opts.spa) {
            var matches = request.uri.match('.*\\.[\\d\\w]+$')
            var negate = true
            if (matches === null && negate||
                matches !== null && ! negate
               ) {
                console.log("Mod rewrite rule matched", matches, '.*\\.[\\d\\w]+$', this.request.uri)
                var handler = new DirectoryEntryHandler(this.fs, this.request)
                handler.rewrite_to = '/index.html'
                this.rewrite_to = handler.rewrite_to
            }
        }

**Comment by terreng** [comment] 2022-01-11 21:08
That's the old code. Please use the [latest](https://github.com/terreng/simple-web-server/blob/8f5ea1b5f3a5e9a22d72ee11f2270c0abb6f9859/WSC/handlers.js#L270).

**Comment by WebScaffolder** [comment] 2022-01-11 21:56
hi, I tried below code too but no luck -

if (this.app.opts.spa) {
            if (!this.request.uri.match(/.*\.[\d\w]+$/)) {
                console.log("Single page rewrite rule matched", this.request.uri);
                this.rewrite_to = this.app.opts.rewriteTo || "/index.html";
            }
        }

**Comment by terreng** [comment] 2022-01-11 22:16
Please confirm that you are no longer running the chrome extension web server. I tested the code and it should work. If not, could you please describe the issue?

**Comment by WebScaffolder** [comment] 2022-01-11 22:37
Hi, it works by your given instruction. if any other issue found I will let you know. thanks for your effort and make it more nicer than old extension.

**Comment by terreng** [comment] 2022-01-11 22:49
Great, I'm glad you figured it out! Thanks again for letting us know about the issue. We'll be releasing the new version of this app soon, so look out for that. Let us know if you find anything else, thanks!

**Closed by terreng** 2022-01-11 22:49 UTC
