### ISSUE TITLE
Basic auth doesn't work correctly with passwords containing colon

### ISSUE THREAD

**Issue by andreimilto** [terreng/simple-web-server#147] opened 2023-07-28 14:53 UTC
*Simple Web Server v1.2.8 win portable*

If basic authentication is used and the password contains `:`, then it's impossible to pass authentication successfully with the valid credentials - error 401 occurs.

The root of the problem must be the call `split(':')` here:
https://github.com/terreng/simple-web-server/blob/f65003ac6381a12482b431a5927757105844c50f/WSC/handlers.js#L174-L183
It is intended to separate the username from the password by splitting the credentials at `:`. But because the password itself contains `:`, the latter gets truncated.
A possible solution would be to use `indexOf(':')` to find the first occurrence of `:` and split credentials at that position.

**Comment by terreng** [comment] 2023-07-28 20:00
Oops. Thanks for catching this and for pinpointing the cause of the issue. It'll be fixed in the next release. (1.2.9)

**Closed** 2023-08-11 03:43 UTC

**Comment by terreng** [comment] 2023-09-05 20:46
Landed in 1.2.9.
